#  todo https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.1.20.pdf
from glsl.v1_10 import *

# method support for “.length()”
gl_PointCoord: vec2  # varing
class mat2x2:...
class mat2x3:...
class mat2x4:...
class mat3x2:...
class mat3x3:...
class mat3x4:...
class mat4x2:...
class mat4x3:...
class mat4x4:...

